routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('/test', function () {
    return view('admin.accueil');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour l'admin
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('admin')->group(function(){
	Route::name('admin.')->group(function () {
		Route::get('/', function () {
		    return view('admin.accueil');
		})->name('index');
		// Professeur
		Route::get('/list-controle', 'Admin\DashboardController@index')->name('get_list_controle');
		Route::get('/liste-professeur', 'Admin\DashboardController@getListProf')->name('get_prof');
		Route::post('/gestion_profs', 'Admin\DashboardController@storeProf')->name('store_prof');
		// Contrôle
		Route::post('/redirect_new_controle', 'Admin\DashboardController@redirectNewControle')->name('redirect_new_controle');
		Route::get('/new_controle/{professeurs}', 'Admin\DashboardController@newControle')->name('new_controle');
		Route::post('/new_controle_document', 'Admin\DashboardController@newControleDocument')->name('new_controle_document');
		// Affichage controlr
		Route::get('/get_controle/{controle}', 'Admin\DashboardController@getControle')->name('get_controle');

		// Route::resource('/gestion_profs', 'Admin\DashboardController@')->only(['store']);

		


	});
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le professeur
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('professeur')->group(function(){
	Route::name('professeur.')->group(function () {
		Route::get('/', 'Professeurs\DashboardController@index')->name('index');
		Route::get('/get_controle/{controle}', 'Professeurs\DashboardController@getControle')->name('get_controle');
		


	});
});

resources/views/partials/includes/formulaires/ajoutCoursForm.blade.php
@inject('auditoires', 'App\Models\Auditoire')
@inject('titulaires', 'App\Models\Titulaire')

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Nouveau cours</h5>
        <button type="button" class="close"  data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        @include('partials._msgFlash')
        {{-- Formulaire --}}
        <form id="etudiantForm" action="{{ route('section.gestion_cours.store') }}" method="POST" name="etudiantForm" class="form-horizontal">
            @csrf
           <input type="hidden" name="idcours" id="fidcours">
           <input type="hidden" name="idauditoires" id="fidauditoires" value="{{ $auditoire->idauditoires }}">
            <div class="form-group">
                <label for="cours"  class="col-sm-2 control-label">Cours</label>
                <div class="col-sm-12">
                    <input type="text"  class="form-control" id="fcours" name="cours" placeholder="Entrer le nom du cours"  maxlength="100" required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="ponderation"  class="col-sm-2 control-label">Ponderation</label>
                <div class="col-sm-12">
                    <input type="number" class="form-control" id="fponderation" name="ponderation" placeholder="Entrer la ponderation du cours"  maxlength="50" required="">
                </div>
            </div>
            <div class="form-group">
                <label for="ponderation"  class="col-sm-2 control-label">Titulaire</label>
                <div class="col-sm-12">
                    <select class="form-control" id="ftitulaire" name="titulaire">
                      <option></option>
                        @foreach($titulaires->get() as $titulaire)
                        <option value="{{ $titulaire->idtitulaires }}">{{ $titulaire->nom .' '. $titulaire->prenom }} </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Auditoire</label>
                <div class="col-sm-12" id="audit">
                    @php 
                    $disabled = !empty($idauditoireSelected) ? 'disabled' : ''; @endphp
                    <select class="form-control" id="fidauditoires" name="idauditoires" required="" {{ $disabled }}>
                        @foreach($auditoires::getAuditoireGroupBySection() as $sections)
                            <optgroup label="{{ $sections[0]->section_lib  }}">
                                @foreach ($sections as $auditoire)
                                    @if(!empty($idauditoireSelected) && $idauditoireSelected == $auditoire->idauditoires)
                                    <option value="{{ $auditoire->idauditoires }}" selected >{{ $auditoire->lib }}</option>
                                    @else
                                    <option value="{{ $auditoire->idauditoires }}"  >{{ $auditoire->lib }}</option>
                                    @endif
                                @endforeach
                            </optgroup>
                        @endforeach
                    </select>
                </div>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
        <button type="submit" class="save btn btn-primary">Enregistrer</button>
      </div>
        </form>
    </div>
  </div>
</div>
@push('scripts')
<script type="text/javascript">
  {{-- Ajout étudiant formulaire --}}
  $(document).on('click', '.addModal', function() {
    $('#msgErrors').html('');
    $('#msgErrors').attr('hidden','true');

    $('.modal-title').text('Ajouter');
    resetmodalData()
    $('.form-horizontal_create').trigger("reset");
    $('.form-horizontal_create').show();
    $('#myModal').modal('show');
    });

  {{-- edition du formulaire --}}
  $(document).on('click', '.edit-modal', function() {
      $('#msgErrors').html('');
      $('#msgErrors').attr('hidden','true');
      $('#footer_action_button').text(" Update");
      $('#footer_action_button').addClass('fa fa-check');
      $('#footer_action_button').removeClass('fa fa-trash');
      $('.actionBtn').addClass('btn-success');
      $('.actionBtn').removeClass('btn-danger');
      $('.actionBtn').removeClass('delete');
      $('.actionBtn').addClass('edit');
      $('.modal-title').text('Modifier');
      $('.deleteContent').hide();
      $('.form-horizontal').show();
      var stuff = $(this).data('info').split(',');
      fillmodalData(stuff)
      $('#myModal').modal('show');
      });

  // remplissage formulaire par les donnée d'une ligne selectionée
  function fillmodalData(details){
      $('#fidcours').val(details[0]);
      $('#fcours').val(details[1]);
      $('#fponderation').val(details[2]);
      $('#ftitulaire').val(details[3]);
      $('#fidauditoires').val(details[4]);
     
      }

  function resetmodalData(){
      $('#fidcours').val('');
      $('#fcours').val('');
      $('#fponderation').val('');
      $('#ftitulaire').val('');
     
      }



  {{-- Suppression  --}}
  $(document).on('click', '.delete-modal', function() {
    $('#footer_action_button').text(" Delete");
    $('#footer_action_button').removeClass('glyphicon-check');
    $('#footer_action_button').addClass('glyphicon-trash');
    $('.actionBtn').removeClass('btn-success');
    $('.actionBtn').addClass('btn-danger');
    $('.actionBtn').removeClass('edit');
    $('.actionBtn').addClass('delete');
    $('.modal-title').text('Delete');
    $('.deleteContent').show();
    $('.form-horizontal').hide();
    var stuff = $(this).data('info').split(',');
    $('.divd').text(stuff[0]);
    $('.dname').html(stuff[1] +" "+stuff[2]);
    $('#myModal').modal('show');
  });

</script>
@endpush

resources/views/partials/includes/formulaires/ajoutEtudiantForm.blade.php
@inject('auditoires', 'App\Models\Auditoire')
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Modifier</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        @include('partials._msgFlash')
        {{-- Formulaire --}}
        <form id="etudiantForm" action="#" method="POST" name="etudiantForm" class="form-horizontal">
            @csrf
           <input type="hidden" name="idetudiants" id="fidetudiants">
            <div class="form-group">
                <label for="matricule"  class="col-sm-2 control-label">Matricule</label>
                <div class="col-sm-12">
                    <input type="text" id="fmatricule" class="form-control" id="matricule" name="matricule" placeholder="Entrer matricule étudiant"  maxlength="50" required="required">
                </div>
            </div>
            <div class="form-group">
                <label for="nom"  class="col-sm-2 control-label">Nom</label>
                <div class="col-sm-12">
                    <input type="text" id="fnom" class="form-control" id="nom" name="nom" placeholder="Entrer nom étudiant"  maxlength="50" required="">
                </div>
            </div>
            <div class="form-group">
                <label for="postnom" class="col-sm-2 control-label">Postnom</label>
                <div class="col-sm-12">
                    <input type="text" id="fpostnom" class="form-control" id="postnom" name="postnom" placeholder="Entrer postnom étudiant"  maxlength="50" >
                </div>
            </div><div class="form-group">
                <label for="prenom"  class="col-sm-2 control-label">Prenom</label>
                <div class="col-sm-12">
                    <input type="text" id="fprenom" class="form-control" id="prenom" name="prenom" placeholder="Entrer prenom étudiant"  maxlength="50" >
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Auditoire</label>
                <div class="col-sm-12">
                    
                	<select class="form-control" id="fidauditoires" name="idauditoires" required="">
                        @foreach($auditoires::getAuditoireGroupBySection() as $sections)
                            <optgroup label="{{ $sections[0]->section_lib  }}">
                                @foreach ($sections as $auditoire)
                                    @if(!empty($idauditoireSelected) && $idauditoireSelected == $auditoire->idauditoires)
                                    <option value="{{ $auditoire->idauditoires }}" selected>{{ $auditoire->lib }}</option>
                                    @else
                                    <option value="{{ $auditoire->idauditoires }}"  >{{ $auditoire->lib }}</option>
                                    @endif
                                @endforeach
                            </optgroup>
                        @endforeach
                	</select>
                </div>
            </div>
        {{--     <div class="col-sm-offset-2 col-sm-10">
             <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
             </button>
            </div> --}}
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
        </form>
      </div>
    </div>
  </div>
</div>

@push('scripts')

@endpush

resources/views/partials/includes/formulaires/newControleForm.blade.php
{{-- Modal --}}
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Nouveau contrôle</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Creation --}}
        <form id="prof_form" action="{{ route('admin.redirect_new_controle') }}" method="POST" name="prof_form" class="form-horizontal_create">
            @csrf
            <input type="text" name="idprofesseurs" hidden="" id="idprofesseurs">
            <div class="form-group">
              <label for="profil"  class="control-label">Professeur</label>
              <div class="col-sm-12">
                @inject('professeurs','App\Models\Professeur')
                  <select class="form-control" id="idprofesseurs" name="idprofesseurs"   required="required">
                @foreach($professeurs->where('user_role','professeur')->get() as $prof)
                    <option value="{{ $prof->idprofesseurs }}">
                      {{ $prof->nom.' '.$prof->postnom.' ' .$prof->prenom }}
                    </option>
                  @endforeach
                  </select>
              </div>
          </div>
              


        @include('partials._msgFlash')
        <div class="modal-footer">
          
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <button type="submit" class="save btn btn-primary">Valider</button>
        </div>
        </form>
        
      </div>
    </div>
  </div>
</div>  