routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('/test', function () {
    return view('admin.accueil');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour l'admin
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('admin')->group(function(){
	Route::name('admin.')->group(function () {
		Route::get('/', function () {
		    return view('admin.accueil');
		})->name('index');
		// Professeur
		Route::get('/list-controle', 'Admin\DashboardController@index')->name('get_list_controle');
		Route::get('/liste-professeur', 'Admin\DashboardController@getListProf')->name('get_prof');
		Route::post('/gestion_profs', 'Admin\DashboardController@storeProf')->name('store_prof');
		// Contrôle
		Route::post('/redirect_new_controle', 'Admin\DashboardController@redirectNewControle')->name('redirect_new_controle');
		Route::get('/new_controle/{professeurs}', 'Admin\DashboardController@newControle')->name('new_controle');
		Route::post('/new_controle_document', 'Admin\DashboardController@newControleDocument')->name('new_controle_document');
		// Affichage controlr
		Route::get('/get_controle/{controle}', 'Admin\DashboardController@getControle')->name('get_controle');

		// Route::resource('/gestion_profs', 'Admin\DashboardController@')->only(['store']);

		


	});
});

/*|||||||||||||||||||||||||||||||||||||
|
|  Routes pour le professeur
|
|||||||||||||||||||||||||||||||||||||*/
Route::prefix('professeur')->group(function(){
	Route::name('professeur.')->group(function () {
		Route::get('/', 'Professeurs\DashboardController@index')->name('index');
		Route::get('/get_controle/{controle}', 'Professeurs\DashboardController@getControle')->name('get_controle');
		


	});
});

resources/views/admin/accueil.blade.php
@extends('layouts.admin-master')
@section('content')
<div class="card " style=" margin-top: 10%;">
  {{-- <div class="card-header">
    Quote
  </div> --}}

  <div class="card-body">
    <div class="row">
    	<div class="col-sm-4">
    		<div class="card text-center text-white bg-primary mb-3" style="max-width: 18rem;">
			  {{-- <div class="card-header">Header</div> --}}
			  <div class="card-body">
			    <button type="button" class="addModal btn btn-primary" data-toggle="modal" data-target="#addModal" >
			    	<h5 class="card-title " ><i class="fas fa-plus-circle fa-2x"></i></h5>
			    	<h5 class="card-text">NOUVEAU CONTRÔLE</h5>
			    </button>
			  </div>
			</div>
    	</div>
    	<div class="col-sm-4">
    		<div class="card text-center text-white bg-primary mb-3" style="max-width: 18rem;">
			  {{-- <div class="card-header">Header</div> --}}
			  <div class="card-body">
			    <a href="{{ route('admin.get_list_controle') }}" class="btn btn-primary">
			    	<h5 class="card-title " ><i class=" fas fa-archive fa-2x"></i></h5>
			    	<h5 class="card-text">ARCHIVES CONTRÔLES</h5>
			    </a>
			  </div>
			</div>
    	</div>
    	<div class="col-sm-4">
    		<div class="card text-center text-white bg-primary mb-3" style="max-width: 18rem;">
			  {{-- <div class="card-header">Header</div> --}}
			  <div class="card-body">
			    <a href="{{ route('admin.get_prof') }}" class="btn btn-primary">
			    	<h5 class="card-title " ><i class=" fas fa-user fa-2x"></i></h5>
			    	<h5 class="card-text">ENSEIGNANTS</h5>
			    </a>
			  </div>
			</div>
    	</div>
    	
    </div>
  </div>
      @include('partials.includes.formulaires.newControleForm')

</div>
@endsection

resources/views/admin/list_controles.blade.php
@extends('layouts.admin-master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="row">
      <div class="col-md-12">
       <h2 class="badge badge-pill badge-info">Contrôle des documents</h2>   
      </div>
  </div>
  <br>
<button type="button" class="addModal btn btn-info" data-toggle="modal" data-target="#addModal">
  		<span class="fas fa-plus"> </span> Nouveau contrôle
	</button><br><br>
<div class="card bg-light mb-3">
  <div class="card-body">
	{!!$dataTable->table() !!}
  </div>
</div>
@include('partials.includes.formulaires.newControleForm')


@endsection
@push('scripts')
{!!$dataTable->scripts() !!}
@endpush

resources/views/admin/list_prof.blade.php
@extends('layouts.admin-master')
@include('partials.includes.dataTables.dataTables')
@include('partials.includes.dataTables.buttons')
@section('content')
<div class="container">
	<button type="button" class="addModal btn btn-info" data-toggle="modal" data-target="#addModal">
  		<span class="fas fa-user-plus"> </span> Nouveau enseignant
	</button><br><br>

	<div class="row">
        <div class="col-md-12">
         <h2 class="badge badge-pill badge-info">Liste des enseignants</h2>   
        </div>
  </div>
	<div class="card bg-light mb-3">
	  <div class="card-body">
		{!!$dataTable->table() !!}
	  </div>
	</div>
</div>

{{-- Modal --}}
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Ajouter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- msg d'erreur --}}
        {{-- Formulaire Creation --}}
        <form id="prof_form" action="{{ route('admin.store_prof') }}" method="POST" name="prof_form" class="form-horizontal_create">
            @csrf
            <input type="text" name="idprofesseurs" hidden="" id="idprofesseurs">
            <div class="form-group">
                  <label for="idsecope"  class="control-label">Identité Secope</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="idsecope" name="idsecope"  maxlength="50" required="">
                  </div>
              </div>
              <div class="form-group">
                  <label for="nom"  class="control-label">Nom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="nom" name="nom"  maxlength="50" required="">
                  </div>
              </div>
              <div class="form-group">
                  <label for="postnom"  class="control-label">Postnom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="postnom" name="postnom"  maxlength="50" >
                  </div>
              </div>
              <div class="form-group">
                  <label for="prenom"  class="control-label">Prenom</label>
                  <div class="col-sm-12">
                      <input type="text"  class="form-control" id="prenom" name="prenom"  maxlength="50" >
                  </div>
              </div>
            <div class="form-group">
	              <label for="attribution"  class="control-label">Attribution</label>
	              <div class="col-sm-12">
	                  <input type="text"  class="form-control" id="attribution" name="attribution"  maxlength="50" required="">
	              </div>
	        </div>
	        <div class="form-group">
	              <label for="qualification"  class="control-label">Qualification</label>
	              <div class="col-sm-12">
	                  <input type="text"  class="form-control" id="qualification" name="qualification"  maxlength="50" required="">
	              </div>
	        </div>
	        <div class="form-group">
	              <label for="anciennete"  class="control-label">Ancienneté</label>
	              <div class="col-sm-12">
	                  <input type="digits"  class="form-control" id="anciennete" name="anciennete"  maxlength="50" required="" >
	              </div>
	        </div>
	        
	       


        @include('partials._msgFlash')
        <div class="modal-footer">
          
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
          <button type="submit" class="save btn btn-primary">Enregistrer</button>
        </div>
        </form>
        
      </div>
    </div>
  </div>
</div>	
@stop
@push('scripts')
{!!$dataTable->scripts() !!}

{{-- Scripts --}}
<script type="text/javascript">
  
  {{-- Ajout étudiant formulaire --}}
  $(document).on('click', '.addModal', function() {
      $('#msgErrors').html('');
      $('#msgErrors').attr('hidden','true');

    $('.modal-title').text('Ajouter');
    resetmodalData()
    $('.form-horizontal').trigger("reset");
    $('.form-horizontal').show();
    $('#myModal').modal('show');
    });

  {{-- edition du formulaire --}}
  $(document).on('click', '.edit-modal', function() {
      $('#msgErrors').html('');
      $('#msgErrors').attr('hidden','true');

      $('#footer_action_button').text(" Update");
      $('#footer_action_button').addClass('fas fa-check');
      $('#footer_action_button').removeClass('fas fa-trash');
      $('.actionBtn').addClass('btn-success');
      $('.actionBtn').removeClass('btn-danger');
      $('.actionBtn').removeClass('delete');
      $('.actionBtn').addClass('edit');
      $('.modal-title').text('Modifier');
      $('.deleteContent').hide();
      $('.form-horizontal').show();
      var stuff = $(this).data('info').split(',');
      fillmodalData(stuff)
      $('#myModal').modal('show');
      });

  // remplissage formulaire par les donnée d'une ligne selectionée
  function fillmodalData(details){
      $('#idprofesseurs').val(details[0]);
      $('#idsecope').val(details[1]);
      $('#nom').val(details[2]);
      $('#postnom').val(details[3]);
      $('#prenom').val(details[4]);
      $('#attribution').val(details[5]);
      $('#qualification').val(details[6]);
      $('#anciennete').val(details[7]);
      
      }

  function resetmodalData(){
      $('#idprofesseurs').val('');
      $('#idsecope').val('');
      $('#nom').val('');
      $('#postnom').val('');
      $('#prenom').val('');
      $('#attribution').val('');
      $('#qualification').val('');
      $('#anciennete').val('');
      
      }



  $('#prof_form').on('submit', function(e) {
    e.preventDefault();
    $('#msgErrors').html('');
        $('#msgErrors').attr('hidden','true');

    $.ajax({
      type: 'post',
      url: '{{ route('admin.store_prof') }}',
      data: {
        '_token': $('input[name=_token]').val(),
        'idprofesseurs': $("#idprofesseurs").val(),
        'idsecope': $("#idsecope").val(),
        'nom': $('#nom').val(),
        'postnom': $('#postnom').val(),
        'prenom': $('#prenom').val(),
        'attribution': $('#attribution').val(),
        'qualification': $('#qualification').val(),
        'anciennete': $('#anciennete').val(),
   
        },

      success: function(data) {
        $('#dataTableBuilder').DataTable().draw(false);
        $('#addModal').modal('hide');
        
      },

          error:function(data) {
            var errors = data.responseJSON.errors;
              $.each(errors, function (key, value) {
                document.getElementById('msgErrors').innerHTML += "<li>"+value+"</li>"
                $('#msgErrors').removeAttr('hidden');
            });
        }
    });
  });

  {{-- Suppression  --}}
  $(document).on('click', '.delete-modal', function() {
    $('#footer_action_button').text(" Delete");
    $('#footer_action_button').removeClass('glyphicon-check');
    $('#footer_action_button').addClass('glyphicon-trash');
    $('.actionBtn').removeClass('btn-success');
    $('.actionBtn').addClass('btn-danger');
    $('.actionBtn').removeClass('edit');
    $('.actionBtn').addClass('delete');
    $('.modal-title').text('Delete');
    $('.deleteContent').show();
    $('.form-horizontal').hide();
    var stuff = $(this).data('info').split(',');
    $('.did').text(stuff[0]);
    $('.dname').html(stuff[1] +" "+stuff[2]);
    $('#myModal').modal('show');
  });

</script>
@endpush

resources/views/admin/new_controle.blade.php
@extends('layouts.admin-master')
@push('stylesheets')
    <link href="{{ asset('matrix/assets/libs/jquery-steps/jquery.steps.css') }}" rel="stylesheet">
    <link href="{{ asset('matrix/assets/libs/jquery-steps/steps.css') }}" rel="stylesheet">
@endpush

@section('content')
      @include('partials._msgFlash')

	<div class="row">
	    <div class="col-md-12">
	     <h2 class="badge badge-pill badge-info">Contrôle des documents | {{ $professeurs->nom .' '.$professeurs->prenom }}</h2>   
	    </div>
	</div>
	<div class="card">
	  <div class="card-header">
	  	<div class="row">
	  		<div class="col-6">
	  			1.ETABLISSEMENT <hr>
	  			Dénomination : {{ env('ETABLISSEMENT_DENOMINATION') }} <br>
	  			Identité Secope : {{ env('ETABLISSEMENT_IDSECOPE') }} <br>
	  			Adresse : {{ env('ETABLISSEMENT_ADRESSE') }} <br>

	  		</div>
	  		<div class="col-6">
	  			2.PROFESSEUR <hr>
	  			Nom,Postnom,Prénom : {{ $professeurs->nom .' '.$professeurs->postnom.' '.$professeurs->prenom }} <br>
	  			Identité Secope : {{$professeurs->idsecope}} <br>
	  			<div class="row">
	  				<div class="col-4">Qualification : {{$professeurs->qualification}}</div>
	  				<div class="col-4">Attribution : {{$professeurs->attribution}}</div>
	  				<div class="col-4">Anciennete : {{$professeurs->anciennete}}</div>
	  			</div>
	  			
	  		</div>
	  	</div>
	  	{{-- Professeur : {{ $professeurs->nom .' '.$professeurs->prenom }}
	  	<br>
	  	Date : {!! date('d-m-Y')!!}
	  	<br>
	  	
	  	<h5><span class="badge badge-pill badge-secondary">Fiche de contrôle</span></h5> --}}
	  </div>
	  <div class="card-body">
	  	<form id="example-form" method="POST" class="m-t-40" action="{{ route('admin.new_controle_document') }}">
            @csrf
            <input type="text" name="idconseillers" hidden value="{{ auth()->user()->idprofesseurs }}">
            <input type="text" name="idprofesseurs" hidden value="{{ $professeurs->idprofesseurs }}">
            <div>
            	@foreach($fiche as $f)
                <h3>{{ $f[0]->types_document }}</h3>
                <section>
                	<div class="row">
            			<div class="col-6"><strong>{{ $f[0]->types_document }}</strong></div>
            			<div class="col-4">
            				<div class="row">
            					<div class="col-9"><strong>Pts</strong></div>
            					<div class="col-3"><strong>Max</strong></div>
            				</div>
            			</div>
            		</div>
            		<hr>
            		@foreach($f as $cote)

            		<div class="row">
            			<div class="col-6">
            				<label for="{{ $cote->slug  }}" style="margin-bottom: 0px">{{ $cote->ponderation }}</label>
            				<p class="text-muted" style="margin-top: 0px;padding-top: 0px">{{ $cote->commentaire }}</p>
            			</div>
            			<div class="col-4">
            				<div class="row">
            					<div class="col-9">
            						<input id="{{ $cote->slug  }}" name="{{ $cote->slug  }}" type="number" max="{{$cote->max}}" class="required form-control">
            					</div>
            					<div class="col-3">/{{ $cote->max }}</div>
            				</div>
            			</div>
            		</div>
            		<hr>
            		@endforeach
                </section>
                @endforeach
                <h3>Rémarques et conseils</h3>
                <section>
                    <div class="row">
                        <div class="col-12">
                            <label for="remarques">Rémarques et conseils</label>
                           	 <textarea class="form-control" id="remarques" name="remarques"></textarea>
                        </div>      
                    </div>
                 </section>
            </div>
        </form>
	  </div>
	  <div class="card-footer text-center">
		{{-- <a href="#" id="send-fiche" class="btn btn-primary btn-block">Envoyer la fiche</a> --}}
	  </div>
	</div>
	
@endsection
@push('scripts')
 <!-- this page js -->
    <script src="{{ asset('matrix/assets/libs/jquery-steps/build/jquery.steps.min.js') }}"></script>
    <script src="{{ asset('matrix/assets/libs/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <script>
        // Basic Example with form
    var form = $("#example-form");
    form.validate({
        errorPlacement: function errorPlacement(error, element) { element.before(error); },
        rules: {
            confirm: {
                equalTo: "#password"
            }
        }
    });
     form.children("div").steps({
        headerTag: "h3",
        bodyTag: "section",
        transitionEffect: "slideLeft",
        onStepChanging: function(event, currentIndex, newIndex) {
            form.validate().settings.ignore = ":disabled,:hidden";
            return form.valid();
        },
        onFinishing: function(event, currentIndex) {
            form.validate().settings.ignore = ":disabled";
            return form.valid();
        },
        onFinished: function(event, currentIndex) {
            form.submit();
        }
    });


    </script>
@endpush

resources/views/admin/view_controle.blade.php
@extends('layouts.admin-master')
@section('content')
<div class="card-header">
  	<div class="row">
		<div class="card-body text-center">
			<strong>ADK/BUREAU SOUS REGIONAL</strong> <br>
			<strong>DES ECOLES CONVENTIONNEES CATHOLIQUES</strong> <br>
			<strong>CONSEILLER : {{ $conseiller->nom .' '. $conseiller->prenom}}</strong> <br>
			<strong>RAPPORT N°ADK/E.C.CATH/CSRF/DJK/R/0{{ $controle->idcontroles_documents }}</strong><br>
		</div>
	</div>
	<div class="row">
		<div class="bordered card-body text-center">
			<h5 class="text-center">INSPECTION PEDAGOGIQUE : CONTRÔLE DES DOCUMENTS DE PROFESSEUR</h5>
		</div>
	</div>
	<div class="row card-body 	">
		<div class="col-6">
			1.ETABLISSEMENT <hr>
			Dénomination : {{ env('ETABLISSEMENT_DENOMINATION') }} <br>
			Identité Secope : {{ env('ETABLISSEMENT_IDSECOPE') }} <br>
			Adresse : {{ env('ETABLISSEMENT_ADRESSE') }} <br>

		</div>
		<div class="col-6">
			2.PROFESSEUR <hr>
			Nom,Postnom,Prénom : {{ $professeur->nom .' '.$professeur->postnom.' '.$professeur->prenom }} <br>
			Identité Secope : {{$professeur->idsecope}} <br>
			<div class="row">
				<div class="col">Qualification : {{$professeur->qualification}}</div>
				<div class="col">Attribution : {{$professeur->attribution}}</div>
				<div class="col">Anciennete : {{$professeur->anciennete}}</div>
			</div>
			
		</div>
	</div>
</div>
  <div class="card-body">
    <div class="row">
	<h5 class="text-center">DOCUMENTS CONTRÔLES</h5>
	</div>
	<div class="row">
		{{-- <div class="col-6"> --}}
			<?php 
				
				$max_total=0;
				$pts_total=0;
			?>
			{{-- @foreach($cotes as $cote) --}}
			<div class=" col-12" style="margin:1%">
			  {{-- <div class="">
			   <strong> {{ $cote[0]->type_documents }} </strong>
			  </div> --}}
			  <div class="">
			    <table class="table table-striped  ">
				  <thead>
				    <tr>
				      <th scope="col"></th>
				      <th scope="col">Pts</th>
				      <th scope="col">Max</th>
				    </tr>
				  </thead>
				  <tbody>
			@foreach($cotes as $cote)
				
				<?php 
					$max=0;
					$pts=0;
				?>
				<tr>
			      {{-- <th scope="col">Désignation</th> --}}
			      <th colspan="3" class="h4">{{ $cote[0]->type_documents }}</th>
			      {{-- <th scope="col">Max</th> --}}
			    </tr>
				  	@foreach($cote as $c)

				  	<?php 
						$max=$max+$c->max;
						$pts=$pts+$c->cote;
					?>
				    <tr>
				      <td>
				      	{{ $c->ponderations }}
				      	<p class="text-muted" style="margin-top: 0px;padding-top: 0px">{{ $c->commentaire }}</p>
				      </td>
				      <td>{{ $c->cote }}</td>
				      <td>{{ $c->max }}</td>
				    </tr>
				   	@endforeach
				   	<tr>
				      <th>Sous-total</th>
				      <th>{{ $pts }}</th>
				      <th>{{ $max }}</th>
				    </tr>
					<?php 
						$max_total=$max+$max_total;
						$pts_total=$pts+$pts_total;
					?>
				  
			@endforeach
					<tr>
				      <td>Remarques et Conseils</td>
				      <td colspan="2">{{ $controle->remarques }}</td>
				      
				    </tr>
				  </tbody>
				</table>
			  </div>
			</div>
			<br>
			
			{{-- @endforeach --}}
		{{-- </div> --}}
	</div>
  </div>
  <div class="card-footer">
    
    <div class="clearfix">
    	<div class="float-left">TOTAL GENERAL : {{ $pts_total .' / '. $max_total }}</div>
    	<div class="float-right">
    		APPRECIATION SYNTHETIQUE : {!! \App\Http\Controllers\Helper::get_appreciation($pts_total) !!}
    	</div>

    </div>
    <hr>
    <div class="clearfix">
    	<div class="float-left">Conseiller d'Enseignement : {{ $conseiller->nom .' '.$conseiller->prenom }} 
    	</div>
    	<div class=" float-right">Fait à Kinshasa: {{ $controle->created_at }}</div>

    </div>
  </div>
</div>
 <br><br>

@endsection